#!/usr/bin/env python
import optparse
import sys
import h5py
import numpy as np
import os.path as path
import os


if __name__=="__main__":
    usage = """%prog [options] h5file
MIP projection of dataset

h5file - volume to check
"""
    parser = optparse.OptionParser(usage=usage)
    parser.add_option('-d', type='str', dest='dataset', default='segmentation/labels', help='[default: %default]')
    parser.add_option('-o', type='str', dest='dir_out', default='mip', help='output_dir [default: %default]')
    '''
    parser.add_option('--swap-xy', action='store_true', dest='swap_xy', help='switches x and y coordinates of the traxels in FILE1')
    parser.add_option('--ignore-z', action='store_true', dest='ignore_z', help='only match in the x-y subspace')
    '''
    options, args = parser.parse_args()

    numArgs = len(args)
    if numArgs == 1:
        fn = args[0]
    else:
        parser.print_help()
        sys.exit(1)

    with h5py.File(fn, 'r') as f:
        volume = f[options.dataset].value
    
    projection = np.max(volume, axis=2)

    if not path.exists( options.dir_out ):
        os.makedirs( options.dir_out )
    with h5py.File(path.join(options.dir_out, fn), 'w') as f:
        f.create_dataset('mip', data=projection)
