#!/usr/bin/env python
import glob
import h5py
from scipy import misc
import optparse
import os
import os.path as path
import sys
import numpy as np
import vigra

from IPython.Shell import IPShellEmbed


def to_tiff_stack( fn, h5path, out_dir, axis=2, prefix='0000', suffix='tif'):
    with h5py.File( fn, 'r') as f:
        data = f[h5path].value
    del f
    for i in range(0,data.shape[axis]):
        if axis==2:
            im = data[:,:,i]
        elif axis==1:
            im = data[:,i,:]
        else:
            im = data[i,:,:]
        out_fn = path.join(out_dir, '%s_%04d.%s' % (prefix,i,suffix) )
        #misc.imsave(out_fn , im)
        vigra.impex.writeImage(im, out_fn)
        print "Saved: " + out_fn

if __name__=="__main__":
    # option parser
    usage = """%prog [options] H5FILE(S)
Convert HDF5 volumetric dataset to a stack of tiff files.

Standard unix GLOB matching (i.e. "*.h5") as well as several filenames are supported as arguments.
"""
    parser = optparse.OptionParser(usage=usage)
    parser.add_option('-d', '--dataset', type='string', dest='src', default='/raw/volume', help='path to HDF5 dataset [default: %default]')
    parser.add_option('-a', '--axis', type='choice', dest='axis', choices=['0','1','2'], default='2', help='0,1 or 2 - convert along axis [default: %default]')
    parser.add_option('-p', '--prefix', type='string', dest='prefix', default='0000', help='output files prefix [default: %default]')
    parser.add_option('-s', '--suffix', type='string', dest='suffix', default='tif', help='determines image format [default: %default]')
    parser.add_option('-o', type='string', dest='out_dir', default='out', help='output directory [default: %default]')

    options, args = parser.parse_args()

    numArgs = len(args)
    if numArgs > 0:
        fns = []
        for arg in args:
            fns.extend(glob.glob(arg))
    else:
        parser.print_help()
        sys.exit(1)
    
    for fn in fns:
        out_dir = "as_tiff-"+path.basename(fn)
        print "Converting " + fn + "..."
        if not path.exists( options.out_dir ):
            os.makedirs( options.out_dir )
        to_tiff_stack( fn, options.src, options.out_dir, int(options.axis), options.prefix, options.suffix)
        print
