#!/usr/bin/env python
import sys
sys.path.append('../.')
sys.path.append('.')

import os
import os.path as path
import getpass
import glob
import optparse
import socket
import time

import numpy as np
import h5py

from empryonic import traininggui

       
if __name__=="__main__":
    usage = """%prog FILES [options]
    Run a graphical user interface to visualize and label objects in Digital Embryos HDF5 files. Random Forest classifiers can be trained and used for predicion.
    
    FILES can be arbitrary many Digital Embryo HDF5 files to be loaded.    
    """
    
    parser = optparse.OptionParser(usage=usage)
    #parser.add_option('-i', '--index', type='int', dest='index', default=0, help="Index of the file to be loaded [default: %default]")

    options, args = parser.parse_args()
    
    numArgs = len(args)
    if numArgs > 0:
        fns = []
        for arg in args:
            fns.extend(glob.glob(arg))
    else:
        parser.print_help()
        sys.exit(1)
    fns.sort()

    
    gui = traininggui.traininggui(fns)
    gui.configure_traits()
