version: 2
## Customize the test machine
jobs:
  build:
    working_directory: ~/hytra/hytra
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CONDA_ROOT: /home/ubuntu/miniconda
      TEST_ENV_NAME: test-env
      TEST_ENV_PREFIX: /home/ubuntu/miniconda/envs/test-env
    docker:
    - image: continuumio/miniconda3
    steps:
    - checkout

    - restore_cache:
        keys:
          # This branch if available
          - 0.1.0-dep-{{ .Branch }}-
          # Default branch if not
          - 0.1.0-dep-master-
          # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
          - 0.1.0-dep-

    - run:
        name: update conda
        command: >
            conda config --set always_yes yes --set changeps1 no --set channel_priority strict &&
            conda update -q conda -c conda-forge -c defaults &&
            conda install -n base -c conda-forge -c defaults conda-build

    - save_cache:
        key: 0.1.0-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - /home/ubuntu/miniconda

    - run:
        name: conda-build-w-tests
        command: conda build -c ilastik-forge -c conda-forge conda-recipe
