package:
  name: hytra
  
  {% set tagged_version = GIT_DESCRIBE_TAG %}

  # If we're using a non-tagged revision, append '.postN' to the version
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}

  version: {{tagged_version}}

source:
  path: ../

build:
  noarch: python
  number: 1000
  string: py_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python  {{ python }}
    - pip

  run:
    - python >=2.7
    - dpct
    - networkx <={{ networkx }}
    - yapsy
    - vigra
    - scikit-learn
    - scikit-image
    - h5py

test:
  source_files:
    - tests/*
    - scripts/*
    - empryonic/*
    - hytra/*
  requires:
    - configargparse
    - nose
    - jinja2
  imports:
    - hytra
  commands:
    - nosetests tests

about:
  home: https://github.com/chaubold/hytra
  license: MIT
  summary: 'Python tracking framework developed at the IAL lab @ University of Heidelberg'
