name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-w-conda-recipe:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
          channel-priority: strict
          miniforge-version: latest
          conda-solver: libmamba
      - name: install build deps
        run: mamba install -n base -c conda-forge conda-build -y
      - name: linux conda build test
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: conda build -c ilastik-forge -c conda-forge conda-recipe
      - name: osx test
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run: conda build -c ilastik-forge -c conda-forge conda-recipe
      - name: windows conda-build
        if: matrix.os == 'windows-latest'
        shell: cmd /C CALL {0}
        run: conda build -c ilastik-forge -c conda-forge conda-recipe
